#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightApplication1.Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class DB_StudentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DB_StudentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_StudentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_StudentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_StudentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TR_Student> TR_Students
		{
			get
			{
				return this.GetTable<TR_Student>();
			}
		}
		
		public System.Data.Linq.Table<TR_Group> TR_Groups
		{
			get
			{
				return this.GetTable<TR_Group>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class TR_Student
	{
		
		private string _td_FirstName;
		
		private string _td_LastName;
		
		private string _td_GroupNumber;
		
		private string _td_MatriculationNumber;
		
		private string _td_Password;
		
		private bool _td_IsApplicationSend;
		
		private bool _td_IsCompleted;
		
		private System.DateTime _td_DateFirstContact;
		
		private System.DateTime _td_DateApplicationSend;
		
		private System.DateTime _td_DateCompletionSend;
		
		private System.DateTime _td_Start;
		
		private System.DateTime _td_End;
		
		private string _td_CompanyName;
		
		private string _td_Departmant;
		
		private string _td_StreetAndNumber;
		
		private string _td_PIN;
		
		private string _td_City;
		
		private string _td_Activity;
		
		private string _td_CoachName;
		
		private string _td_CoachPhone;
		
		private int _td_CompanyRating;
		
		private int _td_InternshipRating;
		
		private string _td_StudentComment;
		
		private bool _td_InternshipAccept;
		
		public TR_Student()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_FirstName", CanBeNull=false)]
		public string td_FirstName
		{
			get
			{
				return this._td_FirstName;
			}
			set
			{
				if ((this._td_FirstName != value))
				{
					this._td_FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_LastName", CanBeNull=false)]
		public string td_LastName
		{
			get
			{
				return this._td_LastName;
			}
			set
			{
				if ((this._td_LastName != value))
				{
					this._td_LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_GroupNumber", CanBeNull=false)]
		public string td_GroupNumber
		{
			get
			{
				return this._td_GroupNumber;
			}
			set
			{
				if ((this._td_GroupNumber != value))
				{
					this._td_GroupNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_MatriculationNumber", CanBeNull=false)]
		public string td_MatriculationNumber
		{
			get
			{
				return this._td_MatriculationNumber;
			}
			set
			{
				if ((this._td_MatriculationNumber != value))
				{
					this._td_MatriculationNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_Password", CanBeNull=false)]
		public string td_Password
		{
			get
			{
				return this._td_Password;
			}
			set
			{
				if ((this._td_Password != value))
				{
					this._td_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_IsApplicationSend")]
		public bool td_IsApplicationSend
		{
			get
			{
				return this._td_IsApplicationSend;
			}
			set
			{
				if ((this._td_IsApplicationSend != value))
				{
					this._td_IsApplicationSend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_IsCompleted")]
		public bool td_IsCompleted
		{
			get
			{
				return this._td_IsCompleted;
			}
			set
			{
				if ((this._td_IsCompleted != value))
				{
					this._td_IsCompleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_DateFirstContact")]
		public System.DateTime td_DateFirstContact
		{
			get
			{
				return this._td_DateFirstContact;
			}
			set
			{
				if ((this._td_DateFirstContact != value))
				{
					this._td_DateFirstContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_DateApplicationSend")]
		public System.DateTime td_DateApplicationSend
		{
			get
			{
				return this._td_DateApplicationSend;
			}
			set
			{
				if ((this._td_DateApplicationSend != value))
				{
					this._td_DateApplicationSend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_DateCompletionSend")]
		public System.DateTime td_DateCompletionSend
		{
			get
			{
				return this._td_DateCompletionSend;
			}
			set
			{
				if ((this._td_DateCompletionSend != value))
				{
					this._td_DateCompletionSend = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_Start")]
		public System.DateTime td_Start
		{
			get
			{
				return this._td_Start;
			}
			set
			{
				if ((this._td_Start != value))
				{
					this._td_Start = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_End")]
		public System.DateTime td_End
		{
			get
			{
				return this._td_End;
			}
			set
			{
				if ((this._td_End != value))
				{
					this._td_End = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_CompanyName", CanBeNull=false)]
		public string td_CompanyName
		{
			get
			{
				return this._td_CompanyName;
			}
			set
			{
				if ((this._td_CompanyName != value))
				{
					this._td_CompanyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_Departmant", CanBeNull=false)]
		public string td_Departmant
		{
			get
			{
				return this._td_Departmant;
			}
			set
			{
				if ((this._td_Departmant != value))
				{
					this._td_Departmant = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_StreetAndNumber", CanBeNull=false)]
		public string td_StreetAndNumber
		{
			get
			{
				return this._td_StreetAndNumber;
			}
			set
			{
				if ((this._td_StreetAndNumber != value))
				{
					this._td_StreetAndNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_PIN", CanBeNull=false)]
		public string td_PIN
		{
			get
			{
				return this._td_PIN;
			}
			set
			{
				if ((this._td_PIN != value))
				{
					this._td_PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_City", CanBeNull=false)]
		public string td_City
		{
			get
			{
				return this._td_City;
			}
			set
			{
				if ((this._td_City != value))
				{
					this._td_City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_Activity", CanBeNull=false)]
		public string td_Activity
		{
			get
			{
				return this._td_Activity;
			}
			set
			{
				if ((this._td_Activity != value))
				{
					this._td_Activity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_CoachName", CanBeNull=false)]
		public string td_CoachName
		{
			get
			{
				return this._td_CoachName;
			}
			set
			{
				if ((this._td_CoachName != value))
				{
					this._td_CoachName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_CoachPhone", CanBeNull=false)]
		public string td_CoachPhone
		{
			get
			{
				return this._td_CoachPhone;
			}
			set
			{
				if ((this._td_CoachPhone != value))
				{
					this._td_CoachPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_CompanyRating")]
		public int td_CompanyRating
		{
			get
			{
				return this._td_CompanyRating;
			}
			set
			{
				if ((this._td_CompanyRating != value))
				{
					this._td_CompanyRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_InternshipRating")]
		public int td_InternshipRating
		{
			get
			{
				return this._td_InternshipRating;
			}
			set
			{
				if ((this._td_InternshipRating != value))
				{
					this._td_InternshipRating = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_StudentComment", CanBeNull=false)]
		public string td_StudentComment
		{
			get
			{
				return this._td_StudentComment;
			}
			set
			{
				if ((this._td_StudentComment != value))
				{
					this._td_StudentComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_InternshipAccept")]
		public bool td_InternshipAccept
		{
			get
			{
				return this._td_InternshipAccept;
			}
			set
			{
				if ((this._td_InternshipAccept != value))
				{
					this._td_InternshipAccept = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class TR_Group
	{
		
		private string _td_GroupName;
		
		private System.DateTime _td_EarliestStartOfInternship;
		
		private System.DateTime _td_LatestStartOfInternship;
		
		private int _td_WorkingDays;
		
		private string _td_GroupNumber;
		
		public TR_Group()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_GroupName", CanBeNull=false)]
		public string td_GroupName
		{
			get
			{
				return this._td_GroupName;
			}
			set
			{
				if ((this._td_GroupName != value))
				{
					this._td_GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_EarliestStartOfInternship")]
		public System.DateTime td_EarliestStartOfInternship
		{
			get
			{
				return this._td_EarliestStartOfInternship;
			}
			set
			{
				if ((this._td_EarliestStartOfInternship != value))
				{
					this._td_EarliestStartOfInternship = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_LatestStartOfInternship")]
		public System.DateTime td_LatestStartOfInternship
		{
			get
			{
				return this._td_LatestStartOfInternship;
			}
			set
			{
				if ((this._td_LatestStartOfInternship != value))
				{
					this._td_LatestStartOfInternship = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_WorkingDays")]
		public int td_WorkingDays
		{
			get
			{
				return this._td_WorkingDays;
			}
			set
			{
				if ((this._td_WorkingDays != value))
				{
					this._td_WorkingDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_td_GroupNumber", CanBeNull=false)]
		public string td_GroupNumber
		{
			get
			{
				return this._td_GroupNumber;
			}
			set
			{
				if ((this._td_GroupNumber != value))
				{
					this._td_GroupNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
